<?php

	$arr_translate =  array(
			
			"listar_empresas"      => array("Lista de Empresas","x","x"),
			
			"empresa" => array("Empresa","x","x"),
			"endereco" => array("Endereço","x","x"),
			"maps_link" => array("Link para Maps","x","x"),
			"tel_princ" => array("Telefone Principal","x","x"),
			"tel_sec" => array("Telefone Secundário","x","x"),
			"cnpj_id" => array("Registro CNPJ/ID","x","x"),
			"site" => array("Site","x","x"),
			"email" => array("Email","x","x"),
			"nome_prop" => array("Nome do Proprietário","x","x"),
			"pais" => array("Pais","x","x"),
			"estado" => array("Estado","x","x"),
			"cidade" => array("Cidade","x","x"),
			"acoes" => array("Ações","x","x"),
			"add_company" => array("Adicionar Companhia","x","x"),
			"deseja_deletar_empresa" => array("Deseja deletar empresa","x","x"),
			"cometarios" => array("Comentarios","x","x"),
			"cad_nome" => array("Nome da Empresa","x","x"),
			"cad_cnpj" => array("CNPJ/ID/Registro da Empresa","x","x"),
			"cad_end" => array("Endereco: Rua/Avenida/Logradouro, Número, Bairro, Apto/Casa/Empresarial etc","x","x"),
			"cad_cidade" => array("Cidade","x","x"),
			"cad_estado" => array("Estado","x","x"),
			"cad_pais" => array("Pais","x","x"),
			"cad_tel_p" => array("Telefone Principal","x","x"),
			"cad_tel_s" => array("Telefone Secundário","x","x"),
			"cad_email" => array("Email","x","x"),
			"cad_site" => array("Site","x","x"),
			"cad_maps" => array("http://.. Link para Maps(Google Maps, Bing, Apple, etc)","x","x"),
			"cad_nome_prop" => array("Nome do propietário ou referência","x","x"),
			"cad_coments" => array("Comentarios sobre a empresa","x","x"),			
			"cad_inserir" => array("Inserir Empresa","x","x"),
			
			"usuario_nao_logado" => array("Usuário não logado.","x","x"),
			"lingua_usu_indefinida" => array("Lingua do usuário nao definida.","x","x"),
			"dig_nome" => array("Digite o nome da empresa","x","x"),
			"dig_end" => array("Digite o endereço da empresa.","x","x"),
			"dig_cidade" => array("Digite a Cidade.","x","x"),
			"dig_estado" => array("Digite o Estado.","x","x"),
			"dig_pais" => array("Digite o Pais.","x","x"),
			"dig_tel_p" => array("Digite o telefone principal.","x","x"),
			"dig_email" => array("Digite o email da empresa.","x","x"),
			"dig_site" => array("Digite o site.","x","x"),
			
			"erros_encontrados" => array("Erros encontrados:","x","x"),
			"email_invalido" => array("Digite um email válido.","x","x"),
			"cadastro_sucesso" => array("Cadastro feito com sucesso.","x","x"),
			"erro_ao_cadastrar" => array("Erro ao cadastrar empresa.","x","x"),
			"verifique_adm_do_sistema" => array("Verifique com o administrador do sistema.","x","x"),
			"dig_site_correto" => array("Digite corretamente o site. Exemplo: http://www...","x","x"),
			"dig_maps_correto" => array("Digite corretamente o endereco de maps. Exemplo: http://maps.google.com....","x","x"),
			"cadastro_empresas" => array("Cadastro de Empresas","x","x"),
			
			"selector_listagem" => array("Listagem de Empresas","x","x"),
			"selector_editar" => array("Editar Empresa","x","x"),
			"selector_cadastrar" => array("Cadastro de Empresas","x","x"),
			"erro_ao_cadastrar" => array("Erro ao tentar cadastrar a empresa. Contacte o administrador.","x","x"),
			"editar_empresa" => array("Editar empresa","x","x"),
			"cad_alterar" => array("Alterar","x","x"),
			"emp_nao_encontrada" => array("Empresa não disponível para edição","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
				
	);

?>