<?php

	$arr_translate =  array(
			
			"usuario_nao_logado"      => array("Usuário não logado.","x","x"),
			"lingua_usu_indefinida" => array("Não é possível definir a lingua.","x","x"),
			"usu_nao_identificado_editar" => array("Usuário não identificado para ser editado.","x","x"),
			"dig_nome_usua" => array("Digite o nome do usuário.","x","x"),
			"def_lingua_usu" => array("Defina a lingua do usuário","x","x"),
			"dig_data_nasc" => array("Digite a data de nascimento.","x","x"),
			"dt_nasc_invalida" => array("Data de nascimento inválida.","x","x"),
			"form_dt_pt_sp_adequado" => array(" Formato adequado: 13/03/1980.","x","x"),
			"form_dt_en_adequado" => array(" Formato adequado: 03/13/1980.","x","x"),
			"dig_email" => array("Digite um email para o usuario.","x","x"),
			"email_invalido" => array("Email inválido.","x","x"),
			"dig_senha" => array("Digite uma senha.","x","x"),
			"formato_senha" => array("Sua senha deve conter: Letras e números, min. de 6 digitos.","x","x"),
			"senhas_identicas" => array("As senhas devem ser identicas.","x","x"),
			"dig_dica_senha" => array("Digite uma dica de senha.","x","x"),
			"sel_privilegios" => array("Selecione os privilégios do usuário.","x","x"),
			"erros_encontrados" => array("Erros encontrados:","x","x"),
			"alter_sucesso" => array("Alteração efetuada com sucesso!","x","x"),
			"email_envi_para_validacao" => array("Uma email foi enviado para validação no seguinte email:","x","x"),
			"email_nao_enviado_validacao" => array("Não foi possivel enviar email de validação para sseguinte email:","x","x"),
			"verifique_adm_do_sistema" => array("Verifique com seu administrador do sistema.","x","x"),
			"erro_ao_editar" => array("Erro ao alterar os dados do usuario!","x","x"),
			"email_ja_existente" => array("Este email já está sendo usado, escolha outro.","x","x"),
			"erro_delete_usuario" => array("Erro ao tentar deletar usuário!","x","x"),
			"delete_usuario_sucesso" => array("Usuário deletado com sucesso.","x","x"),
			
			"listagem_usuar" => array("LISTAGEM DE USUARIOS","x","x"),
			"listagem_nome" => array("NOME","x","x"),
			"listagem_empresa" => array("EMPRESA","x","x"),
			"listagem_email" => array("EMAIL","x","x"),
			"listagem_priv" => array("PRIVILEGIO","x","x"),
			"listagem_dt_nasc" => array("DT. NASC.","x","x"),
			"listagem_lingua" => array("LINGUA","x","x"),
			"listagem_acoes" => array("ACOES","x","x"),
			
			"add_user" => array("ADICIONAR NOVO USUARIO","x","x"),
			
			"lista_cadastro_tit" => array("Cadastro de Usuário:","x","x"),
			"lista_nome_comp" => array("Nome completo","x","x"),
			"lista_dt_nasc" => array("Data de nascimento. Ex: 13/03/1980","x","x"),
			"lista_email" => array("Email","x","x"),
			"lista_senha" => array("Senha: letras e numeros, min. 6 digitos.","x","x"),
			"lista_senha_rep" => array("Repita a senha.","x","x"),
			"lista_dica_senha" => array("Dica de senha","x","x"),
			"lista_priv_text" => array("Privilégio","x","x"),
			"lista_priv_adm" => array("Administrador","x","x"),
			"lista_priv_usuario" => array("Usuário","x","x"),
			"lista_priv_cliente" => array("Cliente","x","x"),
			"lista_lang_text" => array("Lingua","x","x"),
			"lista_lang_pt" => array("Portugues","x","x"),
			"lista_lang_en" => array("Ingles","x","x"),
			"lista_lang_sp" => array("Espanhol","x","x"),
			"lista_empresa" => array("Empresa","x","x"),
			"lista_btn_inserir" => array("INSERIR","x","x"),
			"erro_ao_cadastrar_usua" => array("Erro ao cadastrar usuário. Contacte seu administrador.","x","x"),
			
			"erro_integridade" => array("Erro na integridade dos dados. Contacte o administrador.","x","x"),
			"dica_senha" => array("Dica de senha","x","x"),
			"criacao_sucesso" => array("Usuário criado com sucesso!","x","x"),
			
			"administrador" => array("ADM","x","x"),
			"usuario" => array("USUARIO","x","x"),
			"cliente" => array("CLIENTE","x","x"),
			"indefinido" => array("???","x","x"),
			
			
			"lingua_pt" => array("POR.","x","x"),
			"lingua_en" => array("ENG.","x","x"),
			"lingua_sp" => array("ESP.","x","x"),
			"desc_pt" => array("Porqugues","x","x"),
			"desc_en" => array("Inglês","x","x"),
			"desc_sp" => array("Espanhol","x","x"),
			
			"editar" => array("Editar","x","x"),
			"logout" => array("Logout","x","x"),
			"deseja_sair_sistema" => array("Deseja sair do sistema?","x","x"),
			
			"selector_listagem" => array("Listagem de usuários","x","x"),
			"selector_editar" => array("Editar Usuário","x","x"),
			"selector_cadastrar" => array("Cadastro de Usuários","x","x"),
			"adm" => array("Administrador","x","x"),
			"user" => array("Usuário","x","x"),
			"erro_usuario_localizar" => array("Erro ao tentar localizar usuário.","x","x"),
			"nao_foi_possivel_alterar" => array("Não foi possível cadastrar email. Contacte o administrador.","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
				
	);

?>