<?php

	$arr_translate =  array(						
			"page_not_found" => array("404 - Página não encontrada","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
			"xxxxxxx" => array("xxxx","x","x"),
				
	);

?>